### ISSUE TITLE
improvement #918 lost

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-wmi#7]
(This issue was originally filed by @drenty at https://github.com/elastic/logstash-contrib/issues/34)

---

See: https://github.com/elasticsearch/logstash/commit/06bee7a25f29bb674c5ab58bf51b24c42159942d

Maybe it affects other plugins.

**Comment by ThomasdOtreppe** [comment]
Any update on this? It seems to be an easy fix. Would you like a PR?

**Comment by suyograo** [comment]
@ThomasdOtreppe would love a PR :+1: Thanks in advance!
